name: Bug Report
description: Something is broken or not working as expected
title: "[Bug]: "
labels: ["bug"]
body:
    - type: textarea
      attributes:
          label: What happened?
          description: Describe the issue clearly
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected behaviour
      validations:
          required: true

    - type: input
      attributes:
          label: Browser & version
          placeholder: Chrome 120, Edge 121, etc.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Console errors (if any)
          render: shell

    - type: textarea
      attributes:
          label: Additional context
