name: Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
    - type: textarea
      attributes:
          label: Feature description
          description: What would you like to see added?
      validations:
          required: true

    - type: textarea
      attributes:
          label: Why is this useful?
